[[usage]]
== Usage

To use the plugin, register a dependency by adding it to the `dependencies` block in build.gradle:

[source,java]
[subs="attributes"]
----
dependencies {
   ...
   compile 'org.grails.plugins:spring-security-shiro:{project-version}'
   ...
}
----

and run the `compile` command to resolve the dependencies:

----
$ grails compile
----

This will transitively install the http://grails.org/plugin/spring-security-core[Spring Security Core] plugin, so you'll need to configure that by running the `s2-quickstart` script.

=== Permissions

To use the Shiro annotations and methods you need a way to associate roles and permissions with users. The Spring Security Core plugin already handles the role part for you, so you must configure permissions for this plugin. There is no script to create a domain class, but it's a very simple class and easy to create yourself. It can have any name and be in any package, but otherwise the structure must look like this:

[source,java]
----
package com.mycompany.myapp

class Permission {

   User user
   String permission

   static constraints = {
      permission unique: 'user'
   }
}
----

Register the class name along with the other Spring Security attributes in `application.groovy` (or `application.yml`) using the `grails.plugin.springsecurity.shiro.permissionDomainClassName` property, e.g.

[source,java]
----
grails.plugin.springsecurity.shiro.permissionDomainClassName =
     'com.mycompany.myapp.Permission'
----

You can add other properties and methods, but the plugin expects that there is a one-to-many between your user and permission classes, that the user property name is "`user`" (regardless of the actual class name), and the permission property name is "`permission`".

If you need more flexibility, or perhaps to create this as a many-to-many, you can replace the Spring bean that looks up permissions. Create a class in src/main/groovy that implements the `grails.plugin.springsecurity.shiro.ShiroPermissionResolver` interface, and define the `Set<String> resolvePermissions(String username)` method any way you like. Register your bean as the `shiroPermissionResolver` bean in `resources.groovy`, for example

[source,java]
----
import com.mycompany.myapp.MyShiroPermissionResolver

beans = {
   shiroPermissionResolver(MyShiroPermissionResolver)
}
----

=== Annotated service methods

Currently only Grails services and other Spring beans can be annotated, so this feature isn't available in controllers. You can use any of https://shiro.apache.org/static/1.2.3/apidocs/org/apache/shiro/authz/annotation/RequiresAuthentication.html[RequiresAuthentication], https://shiro.apache.org/static/1.2.3/apidocs/org/apache/shiro/authz/annotation/RequiresGuest.html[RequiresGuest], https://shiro.apache.org/static/1.2.3/apidocs/org/apache/shiro/authz/annotation/RequiresPermissions.html[RequiresPermissions], https://shiro.apache.org/static/1.2.3/apidocs/org/apache/shiro/authz/annotation/RequiresRoles.html[RequiresRoles], and https://shiro.apache.org/static/1.2.3/apidocs/org/apache/shiro/authz/annotation/RequiresUser.html[RequiresUser]. See the https://shiro.apache.org/documentation.html[Shiro documentation] and https://shiro.apache.org/static/1.2.3/apidocs/[Javadoc] for the annotation syntax.

=== Using Shiro directly

You should use the annotations to keep from cluttering your code with explicit security checks, but the standard `Subject` methods will work:

[source,java]
----
import org.apache.shiro.SecurityUtils
import org.apache.shiro.subject.Subject

...

Subject subject = SecurityUtils.getSubject()

subject.checkPermission('printer:print:lp7200')

subject.isPermitted('printer:print:lp7200')

subject.checkRole('ROLE_ADMIN')

subject.hasRole('ROLE_ADMIN')

subject.isAuthenticated()

... etc
----
